name: Build/Publish Docker Container

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/l-tech-arch/ue19-lab-05:latest .

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: ghcr.io/l-tech-arch/ue19-lab-05:latest
          format: table
          ignore-unfixed: true
          exit-code: 0

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/l-tech-arch/ue19-lab-05:latest
